# fly.toml app configuration file generated for rank-orbit-crawler on 2026-05-01T13:02:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rank-orbit-crawler'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  CRAWLER_PORT = '3001'
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'
  PUPPETEER_HEADLESS = 'true'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1024mb'
