import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Sparkles, Zap, CheckCircle, BarChart } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { ComponentPropsWithoutRef } from 'react';
import { AIAnalysis } from '@shared/types';
import AIInsightsLoading from '@/components/loading/AIInsightsLoading';
import AISeoScore from './AISeoScore';
import remarkGfm from 'remark-gfm';

type MarkdownComponentProps = ComponentPropsWithoutRef<'div'> & { node?: unknown };

export default function AIInsightsSection({ data, loading }: { data: AIAnalysis | null, loading: boolean }) {
    if (loading) {
        return <AIInsightsLoading />;
    }

    if (!data) return null;

    return (
        <Card className="h-full bg-white/40 dark:bg-white/5 backdrop-blur-md border-indigo-500/20 shadow-xl shadow-indigo-500/5">
            <CardHeader>
                <div className="flex justify-between items-start">
                    <div>
                        <CardTitle className="flex items-center space-x-2 text-xl">
                            <Sparkles className="w-5 h-5 text-indigo-500 animate-pulse" />
                            <span>AI Executive Summary</span>
                        </CardTitle>
                        <CardDescription>Generated by Gemini AI based on deep analysis.</CardDescription>
                    </div>
                </div>
            </CardHeader>
            <CardContent className="space-y-6">
                <AISeoScore data={data} />

                <div className="bg-gradient-to-br from-indigo-50/50 to-purple-50/50 dark:from-indigo-900/20 dark:to-purple-900/20 p-6 rounded-2xl border border-indigo-100/50 dark:border-white/5">
                    <div className="text-base leading-relaxed text-gray-700 dark:text-gray-200 prose dark:prose-invert max-w-none prose-p:my-6 prose-img:rounded-xl prose-headings:mb-4 prose-headings:mt-8">
                        <h4 className="flex items-center gap-2 font-semibold text-lg mb-4 text-indigo-700 dark:text-indigo-300">
                            <Sparkles className="w-5 h-5" />
                            Analysis Summary
                        </h4>
                        <ReactMarkdown
                            remarkPlugins={[remarkGfm]}
                            components={{
                                strong: ({ node, ...props }: MarkdownComponentProps) => <span className="font-bold text-indigo-700 dark:text-indigo-300" {...props} />,
                                b: ({ node, ...props }: MarkdownComponentProps) => <span className="font-bold text-indigo-700 dark:text-indigo-300" {...props} />,
                            }}
                        >
                            {data.summary || 'No summary available.'}
                        </ReactMarkdown>
                    </div>
                </div>

                {data.recommendations && data.recommendations.length > 0 && (
                    <div className="space-y-4">
                        <h4 className="flex items-center gap-2 font-semibold text-lg text-indigo-700 dark:text-indigo-300">
                            <Zap className="w-5 h-5" />
                            Key Recommendations
                        </h4>
                        <div className="grid gap-3">
                            {(data.recommendations || []).map((rec: string, i: number) => (
                                <div key={i} className="flex gap-3 bg-white/40 dark:bg-white/5 p-4 rounded-xl border border-indigo-50/50 dark:border-white/5 hover:border-indigo-200/50 transition-colors">
                                    <CheckCircle className="w-5 h-5 text-green-500 shrink-0 mt-0.5" />
                                    <div className="text-sm prose dark:prose-invert max-w-none prose-p:my-1 prose-strong:text-indigo-600 dark:prose-strong:text-indigo-400">
                                        <ReactMarkdown
                                            remarkPlugins={[remarkGfm]}
                                            components={{
                                                strong: ({ node, ...props }: MarkdownComponentProps) => <span className="font-semibold text-indigo-600 dark:text-indigo-400 block mb-1" {...props} />,
                                                b: ({ node, ...props }: MarkdownComponentProps) => <span className="font-semibold text-indigo-600 dark:text-indigo-400 block mb-1" {...props} />,
                                            }}
                                        >
                                            {rec}
                                        </ReactMarkdown>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {data.detailed_report && (
                    <div className="space-y-4">
                        <h4 className="flex items-center gap-2 font-semibold text-lg text-indigo-700 dark:text-indigo-300">
                            <BarChart className="w-5 h-5" />
                            Detailed Report
                        </h4>
                        <div className="prose dark:prose-invert max-w-none text-sm bg-white/40 dark:bg-white/5 p-6 rounded-xl border border-indigo-50/50 dark:border-white/5 prose-p:my-4 prose-ul:my-4 prose-li:my-1 prose-table:my-6 prose-th:p-3 prose-td:p-3">
                            <ReactMarkdown
                                remarkPlugins={[remarkGfm]}
                                components={{
                                    table: ({ node, ...props }: MarkdownComponentProps) => <div className="overflow-x-auto my-6 rounded-lg border border-indigo-100/50 dark:border-white/10"><table className="w-full text-left" {...props} /></div>,
                                    thead: ({ node, ...props }: MarkdownComponentProps) => <thead className="bg-indigo-50/80 dark:bg-white/10 text-xs uppercase font-semibold tracking-wider text-indigo-900 dark:text-indigo-100" {...props} />,
                                    th: ({ node, ...props }: MarkdownComponentProps) => <th className="px-4 py-3 border-b border-indigo-100/50 dark:border-white/10 whitespace-nowrap" {...props} />,
                                    td: ({ node, ...props }: MarkdownComponentProps) => <td className="px-4 py-3 border-b border-indigo-50/50 dark:border-white/5" {...props} />,
                                    tr: ({ node, ...props }: MarkdownComponentProps) => <tr className="hover:bg-indigo-50/30 dark:hover:bg-white/5 transition-colors" {...props} />,
                                    strong: ({ node, ...props }: MarkdownComponentProps) => <strong className="font-semibold text-indigo-700 dark:text-indigo-300" {...props} />,
                                }}>
                                {data.detailed_report}
                            </ReactMarkdown>
                        </div>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}
