'use client';

import { motion } from 'framer-motion';
import { Search, Zap, Bot, Globe, Lock, Activity } from 'lucide-react';

const features = [
    {
        icon: <Search className="w-6 h-6 text-indigo-400" />,
        title: 'Deep SEO Analysis',
        description: 'Our crawler analyzes your HTML structure, meta tags, and content hierarchy to find critical ranking factors.'
    },
    {
        icon: <Zap className="w-6 h-6 text-yellow-400" />,
        title: 'Lighthouse Performance',
        description: 'Integrated with Google Lighthouse to measure Core Web Vitals, performance metrics, and accessibility scores.'
    },
    {
        icon: <Bot className="w-6 h-6 text-purple-400" />,
        title: 'AI-Powered Insights',
        description: 'Get human-readable summaries and actionable recommendations generated by advanced LLMs (Gemini Pro).'
    },
    {
        icon: <Globe className="w-6 h-6 text-blue-400" />,
        title: 'Global Crawling',
        description: 'Our distributed microservices architecture ensures fast and reliable crawling from multiple regions.'
    },
    {
        icon: <Lock className="w-6 h-6 text-green-400" />,
        title: 'Secure & Private',
        description: 'We respect your data. Reports are stored securely and only accessible to you.'
    },
    {
        icon: <Activity className="w-6 h-6 text-pink-400" />,
        title: 'Real-time Monitoring',
        description: 'Track your SEO health over time with historical data and trend analysis (Dashboard).'
    }
];

export default function Features() {
    return (
        <section id="features" className="py-24 relative overflow-hidden">
            <div className="w-full max-w-7xl mx-auto px-6 relative z-10">
                <div className="text-center max-w-2xl mx-auto mb-16">
                    <h2 className="text-3xl md:text-5xl font-bold text-gray-900 dark:text-white mb-6">
                        Everything you need to <br />
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-500 to-purple-500">Rank #1</span>
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 text-lg">
                        Rank Orbit combines traditional SEO tools with modern AI to give you the competitive edge.
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {features.map((feature, index) => (
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: index * 0.1 }}
                            whileHover={{ y: -5 }}
                            className="p-8 rounded-2xl bg-white/50 dark:bg-white/5 border border-gray-200 dark:border-white/10 hover:border-indigo-500/50 hover:bg-white dark:hover:bg-white/10 transition-all backdrop-blur-sm group shadow-sm hover:shadow-lg dark:shadow-none"
                        >
                            <div className="w-12 h-12 rounded-lg bg-gray-100 dark:bg-black/50 border border-gray-200 dark:border-white/10 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                                {feature.icon}
                            </div>
                            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">{feature.title}</h3>
                            <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                                {feature.description}
                            </p>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    );
}
